version: '3.4'

services:
    api:
        container_name: node_advance_auth_api
        build:
            context: .
            target: development
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules # Ignore sync from host to container
        env_file: .env

    db:
        container_name: node_advance_auth_api_db
        image: mongo:4.4-focal
        ports:
            - 27017:27017
        volumes:
            - mongo_data:/data/db
        restart: always

volumes:
    mongo_data:
