version: '3.4'

services:
    api:
        container_name: node_advance_auth_api
        build:
            context: .
            target: development
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules # Ignore sync from host to container
        env_file: .env
